name: historydag
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - black
  - flake8
  - pytest
  - pip
  - ete3
  - six
  - graphviz
  - pip:
    - . # installs historydag package from current directory "."
